// <auto-generated />
using System;
using CardApi.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardApi.Migrations
{
    [DbContext(typeof(CardContext))]
    partial class CardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CardApi.Models.BingoCardChallengeModel", b =>
                {
                    b.Property<Guid>("BingoCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("BingoCardId", "ChallengeId");

                    b.ToTable("BingoCardChallenges");
                });

            modelBuilder.Entity("CardApi.Models.BingoCardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Columns")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BingoCards");
                });

            modelBuilder.Entity("CardApi.Models.BingoCardChallengeModel", b =>
                {
                    b.HasOne("CardApi.Models.BingoCardModel", "BingoCard")
                        .WithMany("BingoCardChallengeModels")
                        .HasForeignKey("BingoCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BingoCard");
                });

            modelBuilder.Entity("CardApi.Models.BingoCardModel", b =>
                {
                    b.Navigation("BingoCardChallengeModels");
                });
#pragma warning restore 612, 618
        }
    }
}
