name: .NET Core CI

on:
  push:
    branches: [ main, "Develop" ]
    paths-ignore:
      - '**.gitignore'
      - '**/README.md'
      - '**.dockerignore'
      - '**/stylecop.props'
      - '**/stylecop.ruleset'
      - '**/stylecop.json'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.gitignore'
      - '**/README.md'
      - '**.dockerignore'
      - '**/stylecop.props'
      - '**/stylecop.ruleset'
      - '**/stylecop.json'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./CardApi
    strategy: 
      matrix: 
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.401

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Login To Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    -
        name: Build and push to docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clockbox:latest
